[build]
builder = "nixpacks"
buildCommand = "npm run build && npx prisma generate --schema prisma/schema.prisma"

[deploy]
startCommand = "npx prisma db push --schema prisma/schema.prisma --accept-data-loss && node dist/server.js"
healthcheckPath = "/health"
healthcheckTimeout = 60

[environments.production.variables]
NODE_ENV = "production"
